LineRobot.ตั้งค่า(LineRobotLineColor.black, 7, 700)
LineRobot.ServoKeeper(LineRobotServoKeeper.Up)
LineRobot.ServoKeeper(LineRobotServoKeeper.Leave)
LineRobot.รอการกดปุ่ม(LineRobotButton.A)
basic.showIcon(IconNames.SmallHeart)
LineRobot.เปรียบเทียบค่าเซ็นเซอร์()
LineRobot.รอการกดปุ่ม(LineRobotButton.B)
basic.showIcon(IconNames.Heart)
basic.forever(function () {
    LineRobot.หยุดมอเตอร์_เป็นเวลา(400)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Down)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(400)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Keep)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(400)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Up)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(300)
    LineRobot.เลี้ยวสปิน(LineRobotTurnDirec.Left, 300)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(200)
    LineRobot.เลี้ยวสปิน(LineRobotTurnDirec.Left, 300)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(200)
    LineRobot.วิ่งตามเส้นแล้วเจอเส้นตัด(500, 0.09, 3.4, 200)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(500)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Down)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(400)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Leave)
    LineRobot.หยุดมอเตอร์_เป็นเวลา(400)
    LineRobot.ServoKeeper(LineRobotServoKeeper.Up)
    LineRobot.รอการกดปุ่ม(LineRobotButton.A)
    basic.showIcon(IconNames.Heart)
})
